server:
  extraArgs: ["--auth-mode=server"]

  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - argo.localhost

workflow:
  serviceAccount:
    create: true

artifactRepository:
  s3:
    accessKeySecret:
      name: argo-workflows-secret
      key: AWS_ACCESS_KEY_ID
    secretKeySecret:
      name: argo-workflows-secret
      key: AWS_SECRET_ACCESS_KEY
    bucket: s3://metaflow
    keyFormat: "argo-artifacts/{{workflow.creationTimestamp.Y}}/{{workflow.creationTimestamp.m}}/{{workflow.creationTimestamp.d}}/{{workflow.name}}/{{pod.name}}"
    endpoint: http://minio.minio.svc.cluster.local:9000/
    useSDKCreds: true
    insecure: true
