apiVersion: v1
kind: Secret
metadata:
  name: metaflow-secret
  namespace: metaflow
stringData:
  AWS_ACCESS_KEY_ID: admin
  AWS_SECRET_ACCESS_KEY: password
  METAFLOW_S3_ENDPOINT_URL: http://minio.minio.svc.cluster.local:9000/
  METAFLOW_DEFAULT_METADATA: service
  METAFLOW_DEFAULT_DATASTORE: s3
  METAFLOW_DATASTORE_SYSROOT_S3: s3://metaflow/metaflow
  METAFLOW_DATATOOLS_S3ROOT: s3://metaflow/data
