metaflow-service:
  image:
    repository: netflixoss/metaflow_metadata_service
    tag: "v2.4.3"
  ingress:
    enabled: true
    className: nginx
    hosts:
      - host: metaflow-service.localhost
        paths:
          - path: /
            pathType: ImplementationSpecific
  metadatadb:
    user: postgres
    password: password
    host: postgresql.postgresql.svc.cluster.local
    port: 5432
    name: metaflow
  envFrom:
    - secretRef:
        name: metaflow-secret

metaflow-ui:
  uiBackend:
    image:
      name: netflixoss/metaflow_metadata_service
      tag: "v2.4.3"
    metadatadb:
      user: postgres
      password: password
      host: postgresql.postgresql.svc.cluster.local
      port: 5432
      name: metaflow
    envFrom:
      - secretRef:
          name: metaflow-secret
    # MF_DATASTORE_ROOT & METAFLOW_DATASTORE_SYSROOT_S3
    # metaflowDatastoreSysRootS3:
    # METAFLOW_S3_ENDPOINT_URL
    # metaflowS3EndpointURL:
    # METAFLOW_SERVICE_URL
    # metaflowServiceURL:

  uiStatic:
    image:
      name: public.ecr.aws/outerbounds/metaflow_ui
      tag: "1.3.5-28-ge1cafd7-obp"
    # metaflowUIBackendURL: "http://localhost:8083/api/"

  ingress:
    enabled: true
    className: nginx
    hosts:
      - host: metaflow-ui.localhost
        paths:
          - path: /api
            pathType: ImplementationSpecific

postgresql:
  enabled: false
