metaflow-service:
  image:
    repository: netflixoss/metaflow_metadata_service
    tag: "v2.4.3"
  ingress:
    enabled: true
    className: nginx
    hosts:
      - host: metaflow-service.localhost
        paths:
          - path: /
            pathType: ImplementationSpecific
  metadatadb:
    user: postgres
    password: password
    host: postgresql.postgresql.svc.cluster.local
    port: 5432
    name: metaflow
  env:
    - name: METAFLOW_S3_ENDPOINT_URL
      value: http://minio.minio.svc.cluster.local:9000/

metaflow-ui:
  image:
    repository: netflixoss/metaflow_metadata_service
    tag: "v2.4.3"
  uiImage:
    tag: "1.3.5-10-g5ca12a8-obp"
  ingress:
    enabled: true
    className: nginx
    hosts:
      - host: metaflow-ui.localhost
        paths:
          - path: /api
            pathType: ImplementationSpecific
  metadatadb:
    user: postgres
    password: password
    host: postgresql.postgresql.svc.cluster.local
    port: 5432
    name: metaflow
  env:
    - name: METAFLOW_S3_ENDPOINT_URL
      value: http://minio.minio.svc.cluster.local:9000/
  envFrom:
    - secretRef:
        name: minio-secret
  METAFLOW_DATASTORE_SYSROOT_S3: s3://metaflow/metaflow

postgresql:
  enabled: false
