metaflow-service:
  image:
    tag: "2.3.8-26-g063a949-obp"
  ingress:
    enabled: true
    className: nginx
    hosts:
      - host: metaflow-service.localhost
        paths:
          - path: /
            pathType: ImplementationSpecific
  metadatadb:
    user: postgres
    password: password
    host: postgresql.postgresql.svc.cluster.local
    port: 5432
    name: metaflow

metaflow-ui:
  image:
    tag: "2.3.8-26-g063a949-obp"
  uiImage:
    tag: "1.3.5-10-g5ca12a8-obp"
  ingress:
    enabled: true
    className: nginx
    hosts:
      - host: metaflow-ui.localhost
        paths:
          - path: /api
            pathType: ImplementationSpecific
  metadatadb:
    user: postgres
    password: password
    host: postgresql.postgresql.svc.cluster.local
    port: 5432
    name: metaflow
  envFrom:
    - secretRef:
        name: minio-secret
  METAFLOW_DATASTORE_SYSROOT_S3: ""
  METAFLOW_S3_ENDPOINT_URL: ""

postgresql:
  enabled: false
