apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-container
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/justingodden/ml-platform.git
    targetRevision: HEAD
    path: argocd-repo/apps/dev-container
  destination:
    server: https://kubernetes.default.svc
    namespace: dev-container
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
