ingress:
  enabled: true
  ingressClassName: nginx
  hostname: minio.localhost

apiIngress:
  enabled: true
  ingressClassName: nginx
  hostname: minio-api.localhost
  annotations:
    nginx.org/client-max-body-size: "50m"

auth:
  rootPassword: password
