apiVersion: v1
kind: Pod
metadata:
  name: dev-container
spec:
  containers:
    - image: justingodden/dev-container
      name: dev-container
      env:
        - name: AWS_ACCESS_KEY_ID
          value: admin
        - name: AWS_SECRET_ACCESS_KEY
          value: password
      resources: {}
